language: python
python:
  - 3.7
  - 3.8
  - 3.9
env:
  global:
    TORTOISE_TEST_MODULES=tests.testmodels
matrix:
  include:
  - python: 3.7
    env: TEST_RUNNER=green
    script: green
    after_success: echo
  - python: 3.7
    env: TEST_RUNNER=nose2
    script: "nose2 --plugin tortoise.contrib.test.nose2 --db-module tests.testmodels --db-url sqlite://:memory:"
    after_success: echo
dist: xenial
services:
  - postgresql
  - mysql
cache: pip
install:
  - pip install -r tests/requirements.txt
script:
  - make ci
after_success:
  - coveralls
